// Simulation values use logical canvas pixels and seconds.
export const CFG = Object.freeze({ gravity: 8.15, thrust: 16.3, fuelBurn: 7.5, turnAccel: 5.2, turnDamping: 4.2, maxSpeed: 20, maxAngularSpeed: 3.6, rocketHeight: 41, rocketWidth: 20, legLength: 15, safeHorizontal: 2.4, safeVertical: 3.4, safeAngleDegrees: 12 });

export function rocketPoints(ship) { const c = Math.cos(ship.angle), s = Math.sin(ship.angle); const point = (lx, ly) => ({ x: ship.x + lx * c - ly * s, y: ship.y + lx * s + ly * c }); return { nose: point(0, -22), leftShoulder: point(-10, 16), rightShoulder: point(10, 16), leftLeg: point(-11, 20 + CFG.legLength), rightLeg: point(11, 20 + CFG.legLength) }; }
export function legs(ship) { const p = rocketPoints(ship); return [p.leftLeg, p.rightLeg]; }
export function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
export function step(ship, input, dt) { const turn = (input.right ? 1 : 0) - (input.left ? 1 : 0); ship.angularVelocity += turn * CFG.turnAccel * dt; ship.angularVelocity -= ship.angularVelocity * CFG.turnDamping * dt; ship.angularVelocity = clamp(ship.angularVelocity, -CFG.maxAngularSpeed, CFG.maxAngularSpeed); ship.angle += ship.angularVelocity * dt; if (input.thrust && ship.fuel > 0) { ship.vx += Math.sin(ship.angle) * CFG.thrust * dt; ship.vy -= Math.cos(ship.angle) * CFG.thrust * dt; ship.fuel = Math.max(0, ship.fuel - CFG.fuelBurn * dt); } ship.vy += CFG.gravity * dt; ship.vx = clamp(ship.vx, -CFG.maxSpeed, CFG.maxSpeed); ship.vy = clamp(ship.vy, -CFG.maxSpeed, CFG.maxSpeed); ship.x += ship.vx * dt; ship.y += ship.vy * dt; }
export function landingResult(ship, pad) { const bothLegs = legs(ship).every((leg) => leg.x >= pad.x && leg.x <= pad.x + pad.w && Math.abs(leg.y - pad.y) <= 7); if (!bothLegs) return { ok: false, reason: 'MISSED THE PAD' }; const angle = Math.abs(ship.angle * 180 / Math.PI); if (angle > CFG.safeAngleDegrees) return { ok: false, reason: 'EXCESSIVE TILT' }; if (Math.abs(ship.vx) > CFG.safeHorizontal) return { ok: false, reason: 'HORIZONTAL SPEED' }; if (ship.vy > CFG.safeVertical) return { ok: false, reason: 'VERTICAL SPEED' }; return { ok: true, reason: 'PERFECT TOUCHDOWN' }; }
export function terrainCollision(ship, terrain, groundAt) { const p = rocketPoints(ship); const vertices = [p.nose, p.leftShoulder, p.leftLeg, p.rightLeg, p.rightShoulder]; if (vertices.some((point) => point.y >= groundAt(terrain, point.x))) return true; const outline = vertices.map((point, index) => [point, vertices[(index + 1) % vertices.length]]); for (let i = 1; i < terrain.points.length; i += 1) { const terrainSegment = [terrain.points[i - 1], terrain.points[i]]; if (outline.some(([a, b]) => segmentsIntersect(a, b, terrainSegment[0], terrainSegment[1]))) return true; } return false; }
function segmentsIntersect(a, b, c, d) { const cross = (p, q, r) => (q.x - p.x) * (r.y - p.y) - (q.y - p.y) * (r.x - p.x); const abC = cross(a, b, c), abD = cross(a, b, d), cdA = cross(c, d, a), cdB = cross(c, d, b); return ((abC > 0 && abD < 0) || (abC < 0 && abD > 0)) && ((cdA > 0 && cdB < 0) || (cdA < 0 && cdB > 0)); }
